package content

// Extra challenges and tests for playable lessons that were missing them.
func init() {
	registerChallenges(map[string]Challenge{
		"comments": {
			Type:        "fix_bug",
			Prompt:      "This Go code has comment syntax errors. Fix them!",
			StarterCode: "package main\n\nimport \"fmt\"\n\n# This is a comment\nfunc main() {\n\t/* Print a greeting //\n\tfmt.Println(\"Hello, Go!\")\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\n// This is a comment\nfunc main() {\n\t/* Print a greeting */\n\tfmt.Println(\"Hello, Go!\")\n}",
			ExpectedOut: "Hello, Go!\n",
			Hints:       []string{"Go uses // for single-line comments, not #", "Multi-line comments need /* to open and */ to close"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"types": {
			Type:        "build",
			Prompt:      "Declare variables of different types and print their types using fmt.Printf with %T:\n- an int set to 42\n- a float64 set to 3.14\n- a string set to \"hello\"\n- a bool set to true\nPrint each type on its own line.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t// Declare variables and print their types with %T\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\ta := 42\n\tb := 3.14\n\tc := \"hello\"\n\td := true\n\tfmt.Printf(\"%T\\n\", a)\n\tfmt.Printf(\"%T\\n\", b)\n\tfmt.Printf(\"%T\\n\", c)\n\tfmt.Printf(\"%T\\n\", d)\n}",
			ExpectedOut: "int\nfloat64\nstring\nbool\n",
			Hints:       []string{"%T prints the TYPE of a value", "Use := for short variable declaration"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"interpolation": {
			Type:        "rewrite",
			Prompt:      "Rewrite this JS template literal in Go:\n\nconst name = \"Alice\";\nconst age = 30;\nconsole.log(`Name: ${name}, Age: ${age}`);",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tname := \"Alice\"\n\tage := 30\n\t// Print: Name: Alice, Age: 30\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tname := \"Alice\"\n\tage := 30\n\tfmt.Printf(\"Name: %s, Age: %d\\n\", name, age)\n}",
			ExpectedOut: "Name: Alice, Age: 30\n",
			Hints:       []string{"Use fmt.Printf with %s for strings and %d for integers", "Don't forget the \\n at the end!"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"while_loop": {
			Type:        "build",
			Prompt:      "Write a Go while-style loop that starts at 1 and doubles the value each iteration, printing it. Stop when the value exceeds 100.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t// Start at 1, double each time, print, stop after 100\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tn := 1\n\tfor n <= 100 {\n\t\tfmt.Println(n)\n\t\tn *= 2\n\t}\n}",
			ExpectedOut: "1\n2\n4\n8\n16\n32\n64\n",
			Hints:       []string{"Use 'for condition { }' as a while loop", "n *= 2 doubles the value"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"default_values": {
			Type:        "build",
			Prompt:      "Write a variadic function greet that takes names ...string. If no names given, print \"Hello, World!\". Otherwise print \"Hello, <name>!\" for each name. Test with greet() and greet(\"Alice\", \"Bob\").",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc greet(names ...string) {\n\t// If no names, print Hello, World!\n\t// Otherwise print Hello, <name>! for each\n}\n\nfunc main() {\n\tgreet()\n\tgreet(\"Alice\", \"Bob\")\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc greet(names ...string) {\n\tif len(names) == 0 {\n\t\tfmt.Println(\"Hello, World!\")\n\t\treturn\n\t}\n\tfor _, name := range names {\n\t\tfmt.Printf(\"Hello, %s!\\n\", name)\n\t}\n}\n\nfunc main() {\n\tgreet()\n\tgreet(\"Alice\", \"Bob\")\n}",
			ExpectedOut: "Hello, World!\nHello, Alice!\nHello, Bob!\n",
			Hints:       []string{"Check len(names) == 0 for no arguments", "Variadic params are a slice inside the function"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"iife": {
			Type:        "rewrite",
			Prompt:      "Rewrite this JS IIFE in Go:\n\n(function() {\n  const msg = 'hello from IIFE';\n  console.log(msg);\n})();",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t// Write an immediately invoked function\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tfunc() {\n\t\tmsg := \"hello from IIFE\"\n\t\tfmt.Println(msg)\n\t}()\n}",
			ExpectedOut: "hello from IIFE\n",
			Hints:       []string{"Go IIFE syntax: func() { ... }()", "The () at the end calls the function immediately"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"spread": {
			Type:        "build",
			Prompt:      "Combine two slices []int{1, 2, 3} and []int{4, 5, 6} into one using append with ... and print the result.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\ta := []int{1, 2, 3}\n\tb := []int{4, 5, 6}\n\t// Combine and print\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\ta := []int{1, 2, 3}\n\tb := []int{4, 5, 6}\n\tc := append(a, b...)\n\tfmt.Println(c)\n}",
			ExpectedOut: "[1 2 3 4 5 6]\n",
			Hints:       []string{"Use append(a, b...) to unpack slice b into append", "The ... unpacks the slice like JS spread"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"uint8_arrays": {
			Type:        "build",
			Prompt:      "Create a byte slice from the string \"GoQuest\" and print it, then convert it back to a string and print that.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t// Convert string to []byte, print, convert back, print\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tb := []byte(\"GoQuest\")\n\tfmt.Println(b)\n\ts := string(b)\n\tfmt.Println(s)\n}",
			ExpectedOut: "[71 111 81 117 101 115 116]\nGoQuest\n",
			Hints:       []string{"[]byte(str) converts string to bytes", "string(bytes) converts bytes back to string"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"big_numbers": {
			Type:        "build",
			Prompt:      "Create two big.Int values: a=100 and b=200. Add them and print the result.",
			StarterCode: "package main\n\nimport (\n\t\"fmt\"\n\t\"math/big\"\n)\n\nfunc main() {\n\t// Create big.Int a=100, b=200, add them, print\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"math/big\"\n)\n\nfunc main() {\n\ta := big.NewInt(100)\n\tb := big.NewInt(200)\n\tresult := new(big.Int)\n\tresult.Add(a, b)\n\tfmt.Println(result)\n}",
			ExpectedOut: "300\n",
			Hints:       []string{"big.NewInt(100) creates a *big.Int", "result.Add(a, b) stores a+b in result"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"buffers": {
			Type:        "build",
			Prompt:      "Create a bytes.Buffer, write \"Hello\" and \" World\" to it, then print the final string.",
			StarterCode: "package main\n\nimport (\n\t\"bytes\"\n\t\"fmt\"\n)\n\nfunc main() {\n\t// Use bytes.Buffer to build a string\n}",
			Solution:    "package main\n\nimport (\n\t\"bytes\"\n\t\"fmt\"\n)\n\nfunc main() {\n\tvar buf bytes.Buffer\n\tbuf.WriteString(\"Hello\")\n\tbuf.WriteString(\" World\")\n\tfmt.Println(buf.String())\n}",
			ExpectedOut: "Hello World\n",
			Hints:       []string{"var buf bytes.Buffer creates a zero-value buffer", "buf.WriteString() appends to the buffer"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"stack_trace": {
			Type:        "build",
			Prompt:      "Write a function that panics with \"test error\". Use defer/recover in main to catch it and print \"caught: test error\".",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc boom() {\n\t// panic here\n}\n\nfunc main() {\n\t// defer/recover, then call boom()\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc boom() {\n\tpanic(\"test error\")\n}\n\nfunc main() {\n\tdefer func() {\n\t\tif r := recover(); r != nil {\n\t\t\tfmt.Printf(\"caught: %s\\n\", r)\n\t\t}\n\t}()\n\tboom()\n}",
			ExpectedOut: "caught: test error\n",
			Hints:       []string{"defer func() { recover() }() before the panic call", "recover() returns the panic value"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"stderr": {
			Type:        "rewrite",
			Prompt:      "Rewrite in Go:\nprocess.stderr.write('error occurred\\n')",
			StarterCode: "package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n)\n\nfunc main() {\n\t// Write to stderr\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"os\"\n)\n\nfunc main() {\n\tfmt.Fprint(os.Stderr, \"error occurred\\n\")\n}",
			ExpectedOut: "",
			Hints:       []string{"Use fmt.Fprint(os.Stderr, ...)", "stderr output won't show in Go Playground"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"gzip": {
			Type:        "build",
			Prompt:      "Create a bytes.Buffer, compress the string \"hello world\" with gzip, then decompress it and print the result.",
			StarterCode: "package main\n\nimport (\n\t\"bytes\"\n\t\"compress/gzip\"\n\t\"fmt\"\n\t\"io\"\n)\n\nfunc main() {\n\t// Compress and decompress \"hello world\"\n}",
			Solution:    "package main\n\nimport (\n\t\"bytes\"\n\t\"compress/gzip\"\n\t\"fmt\"\n\t\"io\"\n)\n\nfunc main() {\n\tvar buf bytes.Buffer\n\tw := gzip.NewWriter(&buf)\n\tw.Write([]byte(\"hello world\"))\n\tw.Close()\n\n\tr, _ := gzip.NewReader(&buf)\n\tdata, _ := io.ReadAll(r)\n\tfmt.Println(string(data))\n}",
			ExpectedOut: "hello world\n",
			Hints:       []string{"gzip.NewWriter wraps any io.Writer", "Always Close() the gzip writer to flush"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"promises": {
			Type:        "build",
			Prompt:      "Create a function that returns a channel. Send \"hello\" on it in a goroutine. Receive the value in main and print it.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc greetAsync() chan string {\n\t// Create channel, send \"hello\" in goroutine, return channel\n}\n\nfunc main() {\n\t// Receive and print\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc greetAsync() chan string {\n\tch := make(chan string, 1)\n\tgo func() {\n\t\tch <- \"hello\"\n\t}()\n\treturn ch\n}\n\nfunc main() {\n\tresult := <-greetAsync()\n\tfmt.Println(result)\n}",
			ExpectedOut: "hello\n",
			Hints:       []string{"ch := make(chan string, 1) creates a buffered channel", "<-ch receives a value from the channel"},
			BonusXP:     15,
			BonusCoins:  8,
		},
		"async_await": {
			Type:        "build",
			Prompt:      "Write a function compute that returns a channel. In a goroutine, send the result of 21 * 2. In main, receive and print it.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc compute() chan int {\n\t// Return channel with 21 * 2\n}\n\nfunc main() {\n\tresult := <-compute()\n\tfmt.Println(result)\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc compute() chan int {\n\tch := make(chan int, 1)\n\tgo func() {\n\t\tch <- 21 * 2\n\t}()\n\treturn ch\n}\n\nfunc main() {\n\tresult := <-compute()\n\tfmt.Println(result)\n}",
			ExpectedOut: "42\n",
			Hints:       []string{"Send the computation result on the channel", "<-compute() blocks until a value is available"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"event_emitter": {
			Type:        "build",
			Prompt:      "Create a channel, start a goroutine that reads from it and prints the message. Send \"ping\" on the channel from main.",
			StarterCode: "package main\n\nimport \"fmt\"\n\nfunc main() {\n\t// Create channel, goroutine listener, send \"ping\"\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\nfunc main() {\n\tch := make(chan string)\n\tgo func() {\n\t\tmsg := <-ch\n\t\tfmt.Println(msg)\n\t}()\n\tch <- \"ping\"\n}",
			ExpectedOut: "ping\n",
			Hints:       []string{"make(chan string) creates an unbuffered channel", "Unbuffered channels synchronize sender and receiver"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"timeout": {
			Type:        "build",
			Prompt:      "Use time.After to wait 10 milliseconds, then print \"done\". (We use 10ms instead of 1s so the playground doesn't timeout.)",
			StarterCode: "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc main() {\n\t// Wait 10ms then print\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc main() {\n\t<-time.After(10 * time.Millisecond)\n\tfmt.Println(\"done\")\n}",
			ExpectedOut: "done\n",
			Hints:       []string{"<-time.After(duration) blocks for the specified time", "time.Millisecond is a time.Duration constant"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"interval": {
			Type:        "build",
			Prompt:      "Use time.NewTicker to print \"tick\" 3 times with 10ms intervals, then stop.",
			StarterCode: "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc main() {\n\t// Ticker that prints \"tick\" 3 times\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc main() {\n\tticker := time.NewTicker(10 * time.Millisecond)\n\tcount := 0\n\tfor range ticker.C {\n\t\tfmt.Println(\"tick\")\n\t\tcount++\n\t\tif count == 3 {\n\t\t\tticker.Stop()\n\t\t\tbreak\n\t\t}\n\t}\n}",
			ExpectedOut: "tick\ntick\ntick\n",
			Hints:       []string{"for range ticker.C reads tick events", "ticker.Stop() stops the ticker (like clearInterval)"},
			BonusXP:     10,
			BonusCoins:  5,
		},
		"module_import": {
			Type:        "rewrite",
			Prompt:      "Rewrite this JS import in Go:\nconst fmt = require('fmt')\nconst strings = require('strings')\nfmt.Println(strings.ToUpper('hello'))\n\n(Note: in Go, these are standard library imports)",
			StarterCode: "package main\n\n// Import fmt and strings\n\nfunc main() {\n\t// Print \"hello\" in uppercase using strings.ToUpper\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n)\n\nfunc main() {\n\tfmt.Println(strings.ToUpper(\"hello\"))\n}",
			ExpectedOut: "HELLO\n",
			Hints:       []string{"Use import ( ) with each package on its own line", "strings.ToUpper converts to uppercase"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"documentation": {
			Type:        "build",
			Prompt:      "Write a function Add(a, b int) int with a proper Go doc comment that starts with the function name. Call it and print Add(3, 4).",
			StarterCode: "package main\n\nimport \"fmt\"\n\n// Write Add with doc comment\n\nfunc main() {\n\tfmt.Println(Add(3, 4))\n}",
			Solution:    "package main\n\nimport \"fmt\"\n\n// Add returns the sum of a and b.\nfunc Add(a, b int) int {\n\treturn a + b\n}\n\nfunc main() {\n\tfmt.Println(Add(3, 4))\n}",
			ExpectedOut: "7\n",
			Hints:       []string{"Doc comments start with // and the function name", "Convention: // FuncName does..."},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"logging": {
			Type:        "rewrite",
			Prompt:      "Rewrite in Go using the log package:\nconsole.log(new Date().toISOString(), 'server started')",
			StarterCode: "package main\n\nimport \"log\"\n\nfunc main() {\n\t// Use log.Println\n}",
			Solution:    "package main\n\nimport \"log\"\n\nfunc main() {\n\tlog.Println(\"server started\")\n}",
			ExpectedOut: "",
			Hints:       []string{"log.Println adds timestamp automatically", "log output goes to stderr, so playground may not show it"},
			BonusXP:     5,
			BonusCoins:  3,
		},
		"module_export_usage": {
			Type:        "build",
			Prompt:      "Import the \"strings\" package and use strings.ToUpper to print \"hello\" in uppercase.",
			StarterCode: "package main\n\n// Import the right packages\n\nfunc main() {\n\t// Use strings.ToUpper and print\n}",
			Solution:    "package main\n\nimport (\n\t\"fmt\"\n\t\"strings\"\n)\n\nfunc main() {\n\tfmt.Println(strings.ToUpper(\"hello\"))\n}",
			ExpectedOut: "HELLO\n",
			Hints:       []string{"Import both fmt and strings", "strings.ToUpper returns the uppercase version"},
			BonusXP:     5,
			BonusCoins:  3,
		},
	})

	registerTests(map[string][]TestCase{
		"comments": {
			{Name: "Prints greeting", ExpectedOut: "Hello, Go!\n"},
		},
		"types": {
			{Name: "Prints correct types", ExpectedOut: "int\nfloat64\nstring\nbool\n"},
		},
		"interpolation": {
			{Name: "Formats string correctly", ExpectedOut: "Name: Alice, Age: 30\n"},
		},
		"while_loop": {
			{Name: "Doubles to 64", ExpectedOut: "1\n2\n4\n8\n16\n32\n64\n"},
		},
		"default_values": {
			{Name: "Default and custom greetings", ExpectedOut: "Hello, World!\nHello, Alice!\nHello, Bob!\n"},
		},
		"iife": {
			{Name: "IIFE runs", ExpectedOut: "hello from IIFE\n"},
		},
		"spread": {
			{Name: "Slices combined", ExpectedOut: "[1 2 3 4 5 6]\n"},
		},
		"uint8_arrays": {
			{Name: "String to bytes and back", ExpectedOut: "[71 111 81 117 101 115 116]\nGoQuest\n"},
		},
		"big_numbers": {
			{Name: "Adds big ints", ExpectedOut: "300\n"},
		},
		"buffers": {
			{Name: "Buffer concatenation", ExpectedOut: "Hello World\n"},
		},
		"stack_trace": {
			{Name: "Catches panic", ExpectedOut: "caught: test error\n"},
		},
		"gzip": {
			{Name: "Compress and decompress", ExpectedOut: "hello world\n"},
		},
		"promises": {
			{Name: "Receives from channel", ExpectedOut: "hello\n"},
		},
		"async_await": {
			{Name: "Computes via goroutine", ExpectedOut: "42\n"},
		},
		"event_emitter": {
			{Name: "Sends and receives message", ExpectedOut: "ping\n"},
		},
		"timeout": {
			{Name: "Waits then prints", ExpectedOut: "done\n"},
		},
		"interval": {
			{Name: "Ticks 3 times", ExpectedOut: "tick\ntick\ntick\n"},
		},
		"module_import": {
			{Name: "Imports and uses strings", ExpectedOut: "HELLO\n"},
		},
		"documentation": {
			{Name: "Add function works", ExpectedOut: "7\n"},
		},
		"module_export_usage": {
			{Name: "Calls exported function", ExpectedOut: "HELLO\n"},
		},
		"stderr": {
			{Name: "Writes to stderr", ExpectedOut: ""},
		},
		"logging": {
			{Name: "Logs message", ExpectedOut: ""},
		},
	})
}
